# This is a basic workflow to help you get started with Actions

name: PR_report_send

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      value:
        description: "please enter the recipient email address"
        required: false
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run the script
        run: |
          echo ${{ secrets.GH_TOKEN }} > token.txt
          gh auth login < token.txt
          receiver=${{ github.events.inputs.value }} 
          ./script.sh
